Adding the functions to calculate entropy
rformassspectrometry/MsCoreUtils pull request #115
Opened 2023-05-23 12:30 UTC by mar-garcia

2023-05-23 13:05 UTC, jorainer requested changes
Thanks Mar @mar-garcia for these very nice functions!

Please address the comments and in addition:

- please add unit tests (in a file *tests/test_entropy.R* - see maybe [this](https://github.com/rformassspectrometry/MsCoreUtils/blob/main/tests/testthat/test_ppm.R) for an example.
- please add yourself as a contributor (ctb) to the DESCRIPTION
- please increase the version number (the last number 1.11.6 -> 1.11.7) in DESCRIPTION
- please add an entry to the NEWS.md describing the update/addition.

2023-05-23 13:05 UTC, jorainer commented on R/entropy.R
> +  z <- y*log(y)
you could avoid creating the additional variable `z` here by simply using `-sum(y * log(y))` (note also the white space between `y` and `log`)

Also, no need to use `return` in an R function - the last value will always returned, there is no need for additional `return` function call.

2023-05-23 13:13 UTC, lgatto requested changes
- I'll leave it to Johannes to provide more insight on the value of the metric, but are there any plans to also implement the entropy distance? 
- New functions should come with unit tests. I see that there are simple cases that are presented in the paper that could be implemented.

2023-05-23 13:13 UTC, lgatto commented on R/entropy.R
> +#' @param x `numeric`, intensities of the fragment ions value(s).
the "value(s)" can be dropped

2023-05-23 13:56 UTC, lgatto commented on R/entropy.R
> +#' @param x `numeric`, intensities of the fragment ions(s).
just ions

2023-05-24 08:32 UTC, jorainer commented
Regarding the similarity function: yes, the entropy-based similarity function will be added in a second step.

2023-05-24 09:54 UTC, jorainer approved these changes
Thanks Mar!

2023-05-24 10:51 UTC, merged